stages:
  - build
  - deploy

image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_NAME: hochware-des

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_NAME

deploy:
  stage: deploy
  script:
    - ssh root@85.214.56.221 "docker pull $CI_REGISTRY_IMAGE"
    - ssh root@85.214.56.221 "docker run -d -p 80:80 --name hochware-dos $CI_REGISTRY_IMAGE"


