import {Injectable} from '@angular/core';
import {HttpClient} from '@angular/common/http';
import {Observable, shareReplay} from 'rxjs';

export interface GalleryImage {
  name: string;
  src: string;
  width: number;
  height: number;
}

export interface GalleryFolder {
  name: string;
  path: string;
  folders: GalleryFolder[];
  images: GalleryImage[];
}

/** Loads the photo tree generated by tools/pics/build-pics.py. */
@Injectable({providedIn: 'root'})
export class GalleryService {
  private root$?: Observable<GalleryFolder>;

  constructor(private http: HttpClient) {
  }

  load(): Observable<GalleryFolder> {
    if (!this.root$) {
      this.root$ = this.http.get<GalleryFolder>('assets/pics/manifest.json').pipe(shareReplay(1));
    }
    return this.root$;
  }
}
